apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: alpine
      image: docker.intuit.com/nginx
      envFrom:
        - configMapRef:
            name: example-props
      command:
        - sleep
        - "1800"
